[package]
name = "retrograde"
version = "0.2.0"
authors = ["Dylan McGannon <peltium@gmail.com>"]
edition = "2021"

[dependencies]
# General
dotenv = "^0.15"
bytes = "^1.1.0"
reqwest = { version = "^0.11.7", features = ["blocking"] }
gcp_auth = "^0.3.2"
chrono = "^0.4.13"
settimeout = "^0.1.2"
tokio = "^0.2.6"
csv = "^1.1"

# Firebase custom auth
jwt-simple = "^0.11.4"

# Actix
actix-web = "^3.3.2"
actix-http = "^2.2.0"
actix-identity = "^0.3.1"
actix-rt = "1"
env_logger = "^0.9"
log = "^0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "^0.3"
futures-util = "^0.3.5"
actix-cors = "^0.5.4"

# gRPC
tonic = { version = "0.3", features = ["tls", "tls-roots"] }
prost-types = "0.6"
prost = "0.6"

[build-dependencies]
tonic-build = "0.3" # Builds code from .proto files