[package]
name = "retrograde"
version = "0.2.0"
authors = ["Dylan McGannon <peltium@gmail.com>"]
edition = "2018"

[dependencies]
# General
dotenv = "^0.15"
bytes = "^0.5.6"

# Actix
actix-identity = "^0.2.0"
actix-rt = "^1.1.0"
actix-service = "^1.0.0"
actix-web = "^2.0.0"
env_logger = "^0.7"
log = "^0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "^0.3"
futures-util = "^0.3.5"
actix-http = "^1.0.1"
actix-cors = "^0.2.0"

# gRPC
tonic = { version = "0.3", features = ["tls", "tls-roots"] }
prost-types = "0.6"
prost = "0.6"

[build-dependencies]
tonic-build = "0.3" # Builds code from .proto files