[package]
name = "retrograde"
version = "0.2.0"
authors = ["Dylan McGannon <peltium@gmail.com>"]
edition = "2018"

[dependencies]
# Actix
actix-web = "^2.0.0"
actix-rt = "^1.1.0"
env_logger = "^0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "^0.3"

# gRPC
tonic = { version = "0.3", features = ["tls", "tls-roots"] }
prost-types = "0.6"
prost = "0.6"

[build-dependencies]
tonic-build = "0.3" # Builds code from .proto files