[package]
name = "retrograde"
version = "0.1.0"
authors = ["Dylan McGannon <peltium@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "^0.4"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
diesel = { version = "^1.4", features = ["serde_json", "postgres"] }
log = "^0.4"
env_logger = "^0.7"
rand = "^0.7"
rocket_cors = "^0.5"
openssl = "^0.10" # Needed for Postgres.
diesel_migrations = "^1.4"
time = "^0.1" # Rocket uses v0.1 stucts
csv = "^1.1"
rocket_prometheus = "^0.3"
lazy_static = "1.4"

[dependencies.rocket_contrib]
version = "^0.4"
default-features = false
features = ["json", "diesel_postgres_pool"]

[dev-dependencies]
parking_lot = { version = "^0.10", features = ["nightly"] }