[package]
name = "retrograde"
version = "0.1.0"
authors = ["Dylan McGannon <peltium@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
diesel = { version = "1.4", features = ["postgres"] }
log = "0.4"
env_logger = "0.7"
rand = "0.7"
rocket_cors = "0.5.0"
openssl = "0.10.25" # Needed for Postgres.

[dependencies.rocket_contrib]
version = "0.4"
default-features = false
features = ["json", "diesel_postgres_pool"]