[package]
name = "retrograde"
version = "0.3.0"
authors = ["Dylan McGannon <peltium@gmail.com>"]
edition = "2021"

[dependencies]
# General
dotenv = "^0.15"
bytes = "^1.1.0"
reqwest = { version = "^0.11.7", features = ["blocking"] }
chrono = "^0.4.13"
settimeout = "^0.1.2"
tokio = "^1.26.0"
csv = "^1.1"
firestore = "0.30.3"
struct-path = "^0.2.2"

# Firebase custom auth
jwt-simple = "^0.11.4"

# Actix
actix-web = "^4.3.1"
actix-http = "^3.3.0"
actix-identity = "^0.5.2"
actix-utils = "^3.0.1"
actix-session = { version = "^0.7.2", features = ["cookie-session"] }
env_logger = "^0.10"
log = "^0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "^0.3"
futures-util = "^0.3.5"
actix-cors = "^0.6.4"
