[package]
name = "retrograde"
version = "0.1.0"
authors = ["Dylan McGannon <peltium@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4"
rocket_contrib = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
google-firestore1_beta1 = "1.0"
hyper = "^0.10"
hyper-rustls = "0.6"
yup-oauth2 = "1.0"
base64 = "0.10"