version: '3.7'

services:
  api:
    build:
      context: .
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      PSQL_CONNECTION_STRING: postgres://postgres:postgres@postgres/retrograde

  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=retrograde
    volumes:
      - postgres:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus:/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana

volumes:
  postgres:
  prometheus:
  grafana: