name: CI/CD

on:
  push:
    branches:
    - master

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
        - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: retrograde
    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          components: clippy
          override: true
    - run: rustup component add clippy
    - run: sudo apt-get install libpq-dev
    - name: Check
      uses: actions-rs/cargo@v1
      with:
        command: check
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
    - name: Run clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features -- -Dwarnings

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
    - uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCP_ACCOUNT_CREDENTIALS }}
    - name: Install gcloud Beta Components
      run: gcloud components install beta
    - name: Docker build
      uses: docker://gcr.io/cloud-builders/docker
      with:
        args: build . -t gcr.io/retrograde/retrograde:latest
    - name: Docker push
      run: gcloud auth configure-docker && docker push gcr.io/retrograde/retrograde:latest
    - name: Deploy new cloudrun revision
      run: gcloud beta run deploy retrotools-api --image gcr.io/retrograde/retrograde:latest --platform managed --region=us-east1 --project=${{ secrets.GCP_PROJECT }}