name: CI/CD

on:
  push:
    branches:
    - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          default: true
    - name: Install dependencies
      run: sudo apt-get install libpq-dev
    - name: Check
      uses: actions-rs/cargo@v1
      with:
        command: check
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
    - name: Run clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy -- -Dwarnings

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
    - uses: actions/checkout@v1
    - name: Setup Google Cloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCP_ACCOUNT_CREDENTIALS }}
    - name: Docker build
      uses: docker://gcr.io/cloud-builders/docker
      with:
        args: build . -t gcr.io/retrograde/retrograde:latest
    - name: Docker push
      uses: actions/gcloud/cli@master
      with:
        entrypoint: /bin/sh
        args: "-c \"gcloud auth configure-docker && docker push gcr.io/retrograde/retrograde:latest\""
    - name: Deploy cloud run revision
      uses: actions/gcloud/cli@master
      with:
        entrypoint: /bin/sh
        args: "-c \"gcloud components install beta && gcloud beta run deploy retrograde --image gcr.io/retrograde/retrograde:latest --platform managed --region=asia-northeast1 --project=${{ secrets.GCP_PROJECT }}\""