name: CI/CD

on:
  push:
    branches:
    - master

jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Google Cloud
      uses: actions/gcloud/auth@master
      env:
        GCLOUD_AUTH: ${{ secrets.GCP_ACCOUNT_CREDENTIALS }}
    - name: Docker build
      uses: docker://gcr.io/cloud-builders/docker
      with:
        args: build . -t gcr.io/retrograde/retrograde:latest
    - name: Docker push
      uses: actions/gcloud/cli@master
      with:
        entrypoint: /bin/sh
        args: "-c \"gcloud auth configure-docker && docker push gcr.io/retrograde/retrograde:latest\""