name: CI/CD

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          override: true
      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -Dwarnings

  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: "!contains(github.event.head_commit.message, '[skip ci]') && github.ref == 'refs/heads/master'"
    steps:
      - uses: actions/checkout@v1
      - id: "auth"
        uses: "google-github-actions/auth@v0.4.0"
        with:
          credentials_json: "${{ secrets.GCP_ACCOUNT_CREDENTIALS }}"
      - uses: google-github-actions/setup-gcloud@v0
      - name: Install gcloud Beta Components
        run: gcloud components install beta
      - name: Docker build
        uses: docker://gcr.io/cloud-builders/docker
        with:
          args: build . -t gcr.io/${{ secrets.GCP_PROJECT }}/retrograde:latest
      - name: Docker push
        run: gcloud auth configure-docker && docker push gcr.io/${{ secrets.GCP_PROJECT }}/retrograde:latest
      - name: Deploy new cloudrun revision
        run: gcloud beta run deploy retrotools --image gcr.io/${{ secrets.GCP_PROJECT }}/retrograde:latest --platform managed --region=us-east1 --project=${{ secrets.GCP_PROJECT }}
